//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirutalHarlynPichardoO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosPedido
    {
        public int Productos_Id { get; set; }
        public int Pedidos_Id { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
